enabled: true
profiles:
  - user: Test
    secrets:
      - taps:
        - tap
        - double-tap
        - tap
        action: call-service
        service: input_boolean.toggle
        data:
          entity_id: input_boolean.my_switch
      - taps:
        - tap
        - triple-tap
        - tap
        action: toggle-menu
      - taps:
        - double-tap
        - tap
        - double-tap
        - tap
        action: more-info
        entity_id: timer.laundry
      - taps:
        - triple-tap
        - tap
        action: navigate
        navigation_path: /config/dashboard
      - taps:
        - triple-tap
        - tap
        - triple-tap
        action: navigate
        navigation_path: /media-browser/browser
        navigation_replace: true
      - taps:
        - double-tap
        - tap
        - tap
        action: javascript
        code: |
          if (user_is_admin) {
            location.hash = 'something';
          } 