enabled: true
profiles:
  - user:
    - ElChiniNet
    - Palaus
    secrets:
      - taps:
        - tap
        - double-tap
        - tap
        action: call-service
        service: input_boolean.toggle
        data:
          entity_id: input_boolean.my_switch
  - admin: false
    secrets:
      - taps:
        - tap
        - triple-tap
        - tap
        action: toggle-menu
  - owner: false
    secrets:
      - taps:
        - double-tap
        - tap
        - double-tap
        - tap
        action: more-info
        entity_id: timer.laundry